ARG ARCH=
ARG BASE_TAG=2.0.20210813.1
ARG BASE_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:${BASE_TAG}${ARCH}
ARG PY_VERSION=3.9.6

FROM $BASE_IMAGE as updates
RUN yum upgrade -y; yum clean packages; yum clean headers; yum clean metadata; yum clean all; rm -rfv /var/cache/yum;\
    PY2=`readlink -f /usr/bin/python`;\
    sed "1c\#\!${PY2}" /usr/bin/yum -i ;\
    sed "1c\#\!${PY2}" /usr/libexec/urlgrabber-ext-down -i

FROM updates as pybuild
WORKDIR /opt

ADD https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz /opt/Python-3.9.6.tgz
RUN yum upgrade -y; yum groupinstall "Development tools" -y
RUN yum install -y openssl-devel bzip2-devel libffi-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel libpcap-devel xz-devel expat-devel
RUN yum install -y ncurses-c++-libs ncurses-compat-libs ncurses-devel ncurses-libs ncurses-static
RUN mkdir /opt/python -p
RUN tar xzf Python-3.9.6.tgz
ENV LDFLAGS="-L/opt/local/lib"
ENV CFLAGS="-I/opt/local/include"
RUN cd Python-3.9.6;  ./configure --prefix=/opt/python --with-system-ffi --with-computed-gotos --enable-loadable-sqlite-extensions; make && make altinstall
RUN yum install tar gzip xz -y
RUN cd /opt && tar cf - python | xz -z - > /opt/build-Python-3.9.6.tar.xz

FROM $BASE_IMAGE
WORKDIR /opt
COPY --from=pybuild /opt/build-Python-3.9.6.tar.xz /opt/build-Python-3.9.6.tar.xz
RUN yum upgrade -y; yum install make tar xz gzip -y;\
    PY2=`readlink -f /usr/bin/python`;\
    sed "1c\#\!${PY2}" /usr/bin/yum -i ;\
    sed "1c\#\!${PY2}" /usr/libexec/urlgrabber-ext-down -i;\
    ls /opt;\
    tar xfJ build-Python-3.9.6.tar.xz;\
    rm -rfv build-Python-3.9.6.tar.xz;\
    find /opt/python -name "*.pyc" -delete -print;\
    rm -rfv /opt/python/lib/python3.9/test;\
    yum history undo last -y; yum autoremove -y; yum clean packages; yum clean headers; yum clean metadata; yum clean all; rm -rfv /var/cache/yum;\
    (pip --version && pip install --no-cache-dir pip -U) || curl -sq https://bootstrap.pypa.io/get-pip.py | /opt/python/bin/python3.9	;\
    unlink /usr/bin/python; \
    ln -s /opt/python/bin/python3.9 /usr/bin/python ;\
    ln -s /lib/python2.7/site-packages/amazon_linux_extras /lib/python3.9/site-packages/ ;\
    BASE=$($PY2 -c 'import yum; yb = yum.YumBase(); print(yb.conf.yumvar["basearch"])' | tail -1) ;\
    sed "s/(\"basearch\", None)/(\"basearch\", \"${BASE}\")/g" /usr/lib/python2.7/site-packages/amazon_linux_extras/software_catalog.py -i
ENV PATH=/opt/python/bin:$PATH
WORKDIR /

MAINTAINER john@composex.io
LABEL runtime=python
LABEL version=3.9

CMD ["python"]
