ARG ARCH=
ARG BASE_TAG=2023
ARG BASE_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:${BASE_TAG}
ARG PY_VERSION=3.10.13

FROM $BASE_IMAGE as updates
RUN yum upgrade -y; dnf clean packages; dnf clean headers; dnf clean metadata; dnf clean all; rm -rfv /var/cache/dnf

FROM updates as pybuild
WORKDIR /opt

RUN dnf upgrade -y; dnf groupinstall "Development tools" -y
RUN dnf install -y openssl openssl-devel bzip2-devel libffi-devel zlib-devel bzip2-devel ncurses-devel sqlite-devel readline-devel tk-devel libpcap-devel xz-devel expat-devel
RUN dnf install -y ncurses-c++-libs ncurses-compat-libs ncurses-devel ncurses-libs ncurses-static
RUN mkdir /opt/python -p
RUN dnf install tar gzip xz -y
ADD https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tar.xz /opt/Python-3.10.13.tar.xz
RUN tar Jxf Python-3.10.13.tar.xz
ENV LDFLAGS="-L/opt/local/lib"
ENV CFLAGS="-I/opt/local/include"
WORKDIR /opt/Python-3.10.13
RUN ./configure --prefix=/opt/python --with-computed-gotos --enable-loadable-sqlite-extensions --enable-optimizations
ARG CPU_COUNT="-j 1"
RUN make ${CPU_COUNT} && make altinstall
RUN cd /opt && tar cf - python | xz -z - > /opt/build-Python-3.10.13.tar.xz

FROM $BASE_IMAGE
WORKDIR /opt
COPY --from=pybuild /opt/build-Python-3.10.13.tar.xz /opt/build-Python-3.10.13.tar.xz
ENV PATH=/opt/python/bin:$PATH
RUN dnf upgrade -y; dnf install -y openssl-libs; dnf install make tar xz gzip -y;\
    ls /opt;\
    tar xfJ build-Python-3.10.13.tar.xz;\
    rm -rfv build-Python-3.10.13.tar.xz;\
    find /opt/python -name "*.pyc" -delete;\
    rm -rfv /opt/python/lib/python3.10/test;\
    dnf history undo last -y; dnf autoremove -y; dnf clean packages; dnf clean headers; dnf clean metadata; dnf clean all; rm -rfv /var/cache/dnf;\
    unlink /usr/bin/python; \
    ln -s /opt/python/bin/python3.10 /usr/bin/python ;\
    (pip --version && pip install --no-cache-dir pip -U) || curl -sq https://bootstrap.pypa.io/get-pip.py | /opt/python/bin/python3.10	;\
    pip install setuptools -U


WORKDIR /

MAINTAINER john@composex.io
LABEL runtime=python
LABEL version=3.10

CMD ["python"]
