ARG ARCH=
ARG BASE_TAG=2.0.20220207.1
ARG BASE_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:${BASE_TAG}${ARCH}
FROM $BASE_IMAGE
RUN yum upgrade -y; yum install python3 -y ;\
    amazon-linux-extras || yum install amazon-linux-extras -y ;\
    PY2=`readlink -f /usr/bin/python`; sed "1c\#\!${PY2}" /usr/bin/yum -i                           ;\
    sed "1c\#\!${PY2}" /usr/libexec/urlgrabber-ext-down -i                                          ;\
    yum clean all; rm -rfv /var/cache/yum                                                           ;\
    unlink /usr/bin/python; ln -s /usr/bin/python3 /usr/bin/python ;\
    ln -s /lib/python2.7/site-packages/amazon_linux_extras /lib/python3.7/site-packages/ ;\
    BASE=$($PY2 -c 'import yum; yb = yum.YumBase(); print(yb.conf.yumvar["basearch"])' | tail -1) ;\
    sed "s/(\"basearch\", None)/(\"basearch\", \"${BASE}\")/g" /usr/lib/python2.7/site-packages/amazon_linux_extras/software_catalog.py -i ; \
    curl -s https://bootstrap.pypa.io/get-pip.py | python3     ;\
    pip3 install setuptools -U --no-cache-dir

MAINTAINER john@composex.io
LABEL version=3.7
LABEL runtime=python

CMD ["python"]
