ARG ARCH=
ARG BASE_TAG=2
ARG BASE_IMAGE=public.ecr.aws/amazonlinux/amazonlinux:${BASE_TAG}${ARCH}
FROM $BASE_IMAGE
RUN yum upgrade -y; yum install -y amazon-linux-extras; amazon-linux-extras enable python3.8        ;\
    yum install python3.8 -y; curl https://bootstrap.pypa.io/get-pip.py | python3.8                 ;\
    PY2=`readlink -f /usr/bin/python`; sed "1c\#\!${PY2}" /usr/bin/yum -i                           ;\
    sed "1c\#\!${PY2}" /usr/libexec/urlgrabber-ext-down -i                                          ;\
    yum erase -y amazon-linux-extras; yum clean all; rm -rfv /var/cache/yum                         ;\
    unlink /usr/bin/python; ln -s /usr/bin/python3.8 /usr/bin/python

MAINTAINER john@composex.io
LABEL runtime=python
LABEL version=3.8

ENTRYPOINT ["python"]
